version: "3.1"

services:

  app:
    container_name: cartservice-api
    image: cart-service:0.0.1
    build: ./
    ports:
      - '8003:8003'
    depends_on:
      - mongo


  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password


